/**
 * RAG Agent Configuration
 *
 * Generated by initial-setup.md wizard.
 * Modify directly or re-run the wizard to regenerate.
 *
 * All values can be overridden via environment variables.
 */

export type ChunkingStrategy = "fixed" | "semantic" | "hierarchical";
export type QueryEnhancement = "none" | "multi-query" | "hyde" | "step-back";
export type MemoryStrategy = "single-turn" | "fixed-window" | "summary";
export type UseCase = "customer-support" | "knowledge-base" | "code-assistant" | "custom";

export interface RagConfig {
  // Agent identity
  agentName: string;
  agentDescription: string;
  responseLanguage: string;
  useCase: UseCase;

  // Retrieval
  topK: number;
  similarityThreshold: number;
  chunkSize: number;
  chunkOverlap: number;
  chunkingStrategy: ChunkingStrategy;

  // Query processing
  queryEnhancement: QueryEnhancement;
  multiQueryCount: number; // used when queryEnhancement === "multi-query"

  // Reranking
  enableReranking: boolean;
  rerankTopK: number;

  // Memory / conversation
  memoryStrategy: MemoryStrategy;
  windowSize: number; // used when memoryStrategy === "fixed-window"

  // Streaming
  enableStreaming: boolean;

  // Models — resolved at runtime based on NODE_ENV + available env vars
  llmModel: string;
  embeddingModel: string;
  embeddingDimensions: number;

  // Observability
  enableTracing: boolean;
  tracingProvider: "none" | "langfuse" | "langsmith";
}

// Default config — overridden by /setup wizard answers or env vars
const defaultConfig: RagConfig = {
  agentName: process.env["AGENT_NAME"] ?? "Emilio",
  agentDescription: process.env["AGENT_DESCRIPTION"] ?? "Un asistente personal inteligente que recuerda todo lo que le compartes — vídeos, notas, ideas, enlaces — y te ayuda a recuperar esa información cuando la necesitas.",
  responseLanguage: process.env["AGENT_LANGUAGE"] ?? "es",
  useCase: "custom",

  topK: Number(process.env["RAG_TOP_K"] ?? 10),
  similarityThreshold: Number(process.env["RAG_SIMILARITY_THRESHOLD"] ?? 0.3),
  chunkSize: Number(process.env["RAG_CHUNK_SIZE"] ?? 512),
  chunkOverlap: Number(process.env["RAG_CHUNK_OVERLAP"] ?? 50),
  chunkingStrategy: "fixed",

  queryEnhancement: (process.env["RAG_QUERY_ENHANCEMENT"] as QueryEnhancement) || "multi-query",
  multiQueryCount: 3,

  enableReranking: false,
  rerankTopK: 3,

  memoryStrategy: "fixed-window",
  windowSize: 10,

  enableStreaming: true,

  // Gemini in dev, OpenAI/Anthropic in prod
  llmModel: process.env["GEMINI_MODEL"] ?? "gemini-2.5-flash",
  embeddingModel: "gemini-embedding-001",
  embeddingDimensions: 768,

  enableTracing: Boolean(process.env["LANGFUSE_SECRET_KEY"] || process.env["LANGSMITH_API_KEY"]),
  tracingProvider: process.env["LANGFUSE_SECRET_KEY"]
    ? "langfuse"
    : process.env["LANGSMITH_API_KEY"]
    ? "langsmith"
    : "none",
};

// Presets per use case (applied on top of defaultConfig)
export const useCasePresets: Record<UseCase, Partial<RagConfig>> = {
  "customer-support": {
    chunkSize: 512,
    chunkingStrategy: "fixed",
    queryEnhancement: "multi-query",
    enableReranking: true,
    memoryStrategy: "fixed-window",
    windowSize: 10,
    enableStreaming: true,
  },
  "knowledge-base": {
    chunkSize: 1024,
    chunkingStrategy: "hierarchical",
    queryEnhancement: "step-back",
    enableReranking: false,
    memoryStrategy: "summary",
    enableStreaming: true,
  },
  "code-assistant": {
    chunkSize: 256,
    chunkingStrategy: "semantic",
    queryEnhancement: "multi-query",
    enableReranking: true,
    memoryStrategy: "fixed-window",
    windowSize: 20,
    enableStreaming: true,
  },
  "custom": {}, // No preset overrides
};

export const ragConfig: RagConfig = {
  ...defaultConfig,
  ...useCasePresets[defaultConfig.useCase],
};
