/**
 * RAG Agent Configuration
 *
 * Generated by initial-setup.md wizard.
 * Modify directly or re-run the wizard to regenerate.
 *
 * All values can be overridden via environment variables.
 */

export type ChunkingStrategy = "fixed" | "semantic" | "hierarchical";
export type QueryEnhancement = "none" | "multi-query" | "hyde" | "step-back";
export type MemoryStrategy = "single-turn" | "fixed-window" | "summary";
export type UseCase = "customer-support" | "knowledge-base" | "code-assistant" | "custom";

export interface RagConfig {
  // Agent identity
  agentName: string;
  agentDescription: string;
  responseLanguage: string;
  useCase: UseCase;

  // Retrieval
  topK: number;
  similarityThreshold: number;
  chunkSize: number;
  chunkOverlap: number;
  chunkingStrategy: ChunkingStrategy;

  // Query processing
  queryEnhancement: QueryEnhancement;
  multiQueryCount: number; // used when queryEnhancement === "multi-query"

  // Reranking
  enableReranking: boolean;
  rerankTopK: number;

  // Memory / conversation
  memoryStrategy: MemoryStrategy;
  windowSize: number; // used when memoryStrategy === "fixed-window"

  // Streaming
  enableStreaming: boolean;

  // Models — resolved at runtime based on NODE_ENV + available env vars
  llmModel: string;
  embeddingModel: string;
  embeddingDimensions: number;

  // Observability
  enableTracing: boolean;
  tracingProvider: "none" | "langfuse" | "langsmith";
}

// Default config — overridden by initial-setup.md answers
const defaultConfig: RagConfig = {
  agentName: "RAG Agent",
  agentDescription: "A production-ready RAG agent",
  responseLanguage: "en",
  useCase: "custom",

  topK: Number(process.env["RAG_TOP_K"] ?? 5),
  similarityThreshold: Number(process.env["RAG_SIMILARITY_THRESHOLD"] ?? 0.7),
  chunkSize: Number(process.env["RAG_CHUNK_SIZE"] ?? 512),
  chunkOverlap: Number(process.env["RAG_CHUNK_OVERLAP"] ?? 50),
  chunkingStrategy: "fixed",

  queryEnhancement: "none",
  multiQueryCount: 3,

  enableReranking: false,
  rerankTopK: 3,

  memoryStrategy: "fixed-window",
  windowSize: 10,

  enableStreaming: true,

  // Model selection: prod uses OpenAI/Anthropic, local uses Ollama
  llmModel: process.env["NODE_ENV"] === "production"
    ? "claude-3-5-sonnet-20241022"
    : (process.env["OLLAMA_LLM_MODEL"] ?? "mistral"),
  embeddingModel: process.env["NODE_ENV"] === "production"
    ? "text-embedding-3-small"
    : (process.env["OLLAMA_EMBED_MODEL"] ?? "nomic-embed-text"),
  embeddingDimensions: process.env["NODE_ENV"] === "production" ? 1536 : 768,

  enableTracing: Boolean(process.env["LANGFUSE_SECRET_KEY"] || process.env["LANGSMITH_API_KEY"]),
  tracingProvider: process.env["LANGFUSE_SECRET_KEY"]
    ? "langfuse"
    : process.env["LANGSMITH_API_KEY"]
    ? "langsmith"
    : "none",
};

// Presets per use case (applied on top of defaultConfig)
export const useCasePresets: Record<UseCase, Partial<RagConfig>> = {
  "customer-support": {
    chunkSize: 512,
    chunkingStrategy: "fixed",
    queryEnhancement: "multi-query",
    enableReranking: true,
    memoryStrategy: "fixed-window",
    windowSize: 10,
    enableStreaming: true,
  },
  "knowledge-base": {
    chunkSize: 1024,
    chunkingStrategy: "hierarchical",
    queryEnhancement: "step-back",
    enableReranking: false,
    memoryStrategy: "summary",
    enableStreaming: true,
  },
  "code-assistant": {
    chunkSize: 256,
    chunkingStrategy: "semantic",
    queryEnhancement: "multi-query",
    enableReranking: true,
    memoryStrategy: "fixed-window",
    windowSize: 20,
    enableStreaming: true,
  },
  "custom": {}, // No preset overrides
};

export const ragConfig: RagConfig = {
  ...defaultConfig,
  ...useCasePresets[defaultConfig.useCase],
};
